### PR TITLE
Add loading animations to images

### LINKED ISSUE #33: Image loading placeholders in company list
Company List can be slow to load due to all the logos + cover images
Would be nice if logos and cover image showed some subtle css loading animation while image loads

([Notion page](https://www.notion.so/Animate-Image-Loads-Company-List-42c635038d1241e8b2b31248b4b40612))

### PR DESCRIPTION
**Pull request by danrocha**
Created using [v-lazy-image](https://github.com/alexjoverm/v-lazy-image)
Still not perfect, as the SVG loader will enlarge with the image (visible in the company header, for example), but it's nothing serious.
We can later implement our own solution, or try another plugin to fix it. 

Fixes #33

### CODE REVIEW

**Review by gtalarico — APPROVED** [review]
Haven't tested but implementation looks good!
Thanks!

**Comment by danrocha** [comment]
Do you have Netlify PR Previews setup? This way I could also try to test it once I create the PR.
I am not authorized to merge though, so I leave that to you :)

**Comment by gtalarico** [comment]
WRT Netlif see https://github.com/aecworks/aec.works-web/issues/26
You should be able to merge now - I wanted to disallow direct pushes to master and I think instead I disallowed protected merging into it instead

**Comment by gtalarico** [comment]
rebased of master to allow preview

**Pull request merged**
