### PR TITLE
Adds Sorting👇 👆 

### PR DESCRIPTION
**Pull request by gtalarico**
* adds sorting options under hashtag - open to ideas for other design options (@danrocha @daneyul)
* defaults to "last updated"
* sort modes are stored and restored from url
* clicking a selected mode will reverse it (shows icon)

### Preview
image

### CODE REVIEW

**Comment by danrocha** [comment]
Sorting: 💯 
But sorting by clapping doesn't seem to be working in the preview?

I will work on a suggestion for the "reverse" arrow... feels off now...

Not loving the large spacing in the little "about" paragraph, it makes the text disconnected and reads, at first glance, as 4 separate items... wdyt?

**Comment by gtalarico** [comment]
> Not loving the large spacing in the little "about" paragraph, it makes the text disconnected and reads, at first glance, as 4 separate items... wdyt?

good eye, that was by accident.  I was testing a wider line-height on about page but forgot to fix.
has been reverted!

> But sorting by clapping doesn't seem to be working in the preview?
checking now

> I will work on a suggestion for the "reverse" arrow... feels off now...
don't like either... got lazy :)  go for it!

**Comment by danrocha** [comment]
I'll work on it later today! 👍

**Comment by gtalarico** [comment]
> But sorting by clapping doesn't seem to be working in the preview?

It was a staging only issued and caused by a corrupt image. 
culprit was removed and future errors will be handled and logged 👇
https://github.com/aecworks/aec.works-api/pull/73

**Pull request merged**
