### PR TITLE
Show company claps

### PR DESCRIPTION
**Pull request by gtalarico**
Testing adding companies a user clapped for in profile:

image

### CODE REVIEW

**Comment by danrocha** [comment]
Cool idea.
It made me wonder about the overall language/tone that we use throughout the site. Mr. Poopee would maybe write something more cute or funny or cool instead of "Companies Liked" or "Recent Tweets"? 
I am fine with the way it is, just food-for-thought :)

**Comment by gtalarico** [comment]
I would say the tone should be informal and direct. And selectively playful. 
Whatever that means 🤣 

Any ideas you had for these specific instances?

**Comment by danrocha** [comment]
How about something in the 1st person?

"Companies I like", "Companies I'm a fan of:", "I am a fan of..."
"What have I been tweeting about", "My latest tweets:"

Or sth in that direction?

**Comment by gtalarico** [comment]
> "Companies I like", "Companies I'm a fan of:", "I am a fan of..."
"What have I been tweeting about", "My latest tweets:"

I like the tone of those examples
Currently, `Person`  page is the same content whether you are on your own, or viewing someone else profile
so we might need to fork the text for self or someone else

**Comment by danrocha** [comment]
It could still be in the first person even if I am looking at someone else’s profile… gives the feeling I am looking at what that person is showing me.

**Comment by gtalarico** [comment]
Renamed company liked header, left tweet list title because for some reason I embedded title in twitter feed component 🤦

**Pull request merged**
