### PR TITLE
Add location autocomplete

### LINKED ISSUE #17: Address City Auto-Complete
When adding/editing a company, the Location field is a free-text input.
This ticket adds an autocomplete to autocomplete by city name.
This will help ensure the location is consistent and city-based.
Screenshot 2020-09-26 at 09 23 37

### PR DESCRIPTION
**Pull request by danrocha**
Fixes #17 

Uses Google Maps API and Places API add autocomplete to the location field.

- Current API key is hard-coded in the gmap.js file; this is usually not a problem with Google Maps keys because they are meant to be public (access control needs to be configured in Google Credentials), but we could easily move it to an environment variable on Netlify for peace-of-mind...

- Although the autocomplete returns city, country, and coordinates from Google, we are only adding city name to the database. Should we include a `country` field as well?

### CODE REVIEW

**Comment by gtalarico** [comment]
Nicely done 🎉 

> Current API key is hard-coded in the gmap.js file
The only advantage storing in netlify would be if we want to configure different keys per environment which is not needed at this time so I agree this is fine!

> Although the autocomplete returns city

We currently store a mix of city/country since it was freeform city and or country (eg `San Francisco, CA, USA`, `Iceland`)

Showing country is good in cases where the city is not well known, but also repetitive since most entries are generally from well-known cities. Not sure...  @aecworks/aecworks-frontend-devs 



image

image

**Review by gtalarico — APPROVED** [review]
🔥

**Comment by danrocha** [comment]
We should save the city AND country together with the company.
Not necessarily to show in the listing. But this would allow us to later filter by country, or disambiguate city names, or build a little map if we ever want to...

**Comment by gtalarico** [comment]
if we take both we probably want to split location field into city and
country in db model. If you want to take a shortcut for now we can store
just City or 'City, Country' and normalize fields later.

**Comment by danrocha** [comment]
ok, so for now I will return "city, country" as a string.
will update this pull request soon.

**Pull request merged**
